import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../App';
import { Card, CardHeader, CardTitle, CardContent } from './ui/card';
import { Button } from './ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Progress } from './ui/progress';
import { Badge } from './ui/badge';
import { User, Trophy, Wallet, Star, Shield, Timer, TrendingUp, Award, Target, DollarSign, Users, ChevronRight, Home, RotateCcw } from 'lucide-react';
import { TESTIDS } from '../testing/testids';
